### ISSUE TITLE
Doc strings should contain valid utf8 strings

### ISSUE THREAD

**Issue by pyscripter** [Embarcadero/DelphiVCL4Python#15]
There was a [report](https://github.com/pyscripter/pyscripter/issues/1163) regarding introspection of delphivcl in PyScripter.  It turns out this was due to an invalid docstring of Application.ExeName.

Docstrings should be either ascii or else utf8 encoded.   The problem was fixed in https://github.com/pyscripter/python4delphi https://github.com/pyscripter/python4delphi/commit/993c8093651660f1c0e140f7a037c93325930d72.

Please fix on your side.

**Comment by lmbelo** [comment]
@pyscripter thank you for the update information. We are proceeding with the fix.

**Comment by lmbelo** [comment]
We are closing this issue once it was already done and released on the current version.
