### ISSUE TITLE
Minimize window button doesn't work

### ISSUE THREAD

**Issue by Ariel-MN** [Embarcadero/DelphiVCL4Python#16]
I've noticed that the minimize window button doesn't work, either writing the application in Python from scratch or exporting the GUI from Delphi.

**Comment by lmbelo** [comment]
Can you provide the script you're running on to simulate this case?

**Comment by Priyatham10** [comment]
Thank you for noticing the problem. We shall revert as it is solved. We appreciate you raising any further issues you face.

**Comment by excript** [comment]
When placing the mouse over any button in the window, the focus of the region where the pointer is is apparently removed. For example, Windows 10 changes the color of the close button when you place the mouse over it, however, the color immediately returns to the state as if the mouse was not positioned.

![image](https://user-images.githubusercontent.com/10388739/155264934-c95bdf26-baf7-4ee7-95c7-758e64d450c1.png)

It's hard to even get the print!

**Comment by Priyatham10** [comment]
@Ariel-MN Do you observe the issue mentioned by @excript ? It doesn't happen to me. @excript , could you please upload your code as python files for investigation? Because this is a long code from the application visibility.

**Comment by Ariel-MN** [comment]
No, I don't have that problem.

**Comment by excript** [comment]
Video where you can see that the color of the buttons changes when the mouse hovers over.

https://www.youtube.com/watch?v=v-IjLThkx8I

Note that similar to when a control loses focus, I move the mouse pointer over the buttons several times to demonstrate that in a matter of milliseconds the image of the close button switches between red and the default color of Windows.

**Comment by lmbelo** [comment]
@Ariel-MN have you tried to set the MainFormOnTaskBar = True? Set it after the Application.Initialize routine.

```
def main():
    Application.Title = "Checking DelphiVCL4Python"
    Application.Initialize()
    Application.MainFormOnTaskBar = True    
    Main = MainForm(Application)
    Main.Show()
    Application.Run()
    Main.Destroy()
```

Let me know if you have success.

**Comment by Ariel-MN** [comment]
@lmbelo Sorry, that didn't solve the problem.

**Comment by lmbelo** [comment]
That is odd, it should work. We can have I look on it when we connect remotely as well.

**Comment by lmbelo** [comment]
![minimize_function](https://user-images.githubusercontent.com/8376898/160198161-54d49b72-a5ca-4918-bcaf-d5f8e7c331d9.gif)

**Comment by Ariel-MN** [comment]
@lmbelo This did solve the minimizing problem, I got confused thinking it was issue #18. I confirm that adding that line solves the problem.

**Comment by lmbelo** [comment]
Wow, that's great! So I'm closing this issue once it has been resolved.
Thank you for all support.

**Comment by Ariel-MN** [comment]
Nice, I hope that MainFormOnTaskBar = True can be the default in future versions. Happy to help

**Comment by shaunroselt** [comment]
> Nice, I hope that MainFormOnTaskBar = True can be the default in future versions. Happy to help

I hope this gets set to True by default in future versions also.

Someone also had the same issue posted on StackOverflow: https://stackoverflow.com/a/75582372/2908017

**Comment by lmbelo** [comment]
Hmm... It makes sense to set it to true as default. I will have a detailed look at it and investigate for further impacts.

**Comment by lmbelo** [comment]
Yes, this is set by default in the .dpr file. That is why we have let it on user's code instead.

https://github.com/Embarcadero/DelphiVCL4Python/issues/16#issuecomment-1079419917
