### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by Ariel-MN** [Embarcadero/DelphiVCL4Python#17]
There are still some Delphi components that are not supported in the Python export, such as Windows10 -> TNumberBox, if any of these components are present in the exported unit, the application does not run or trigger any errors. It would be helpful to have the cause to quickly identify the problem.

**Comment by lmbelo** [comment]
@Ariel-MN we're wrapping types and event handlers step-by-step. Can you provide all those types/events you're not able to use?

**Comment by Ariel-MN** [comment]
It would certainly be great, although I opened this Issue to report the absence of an error message that made me lose an hour to understand. I think this error message is quite important for those who build the GUI from Delphi and inadvertently use components that are not included in this library yet.

**Comment by lmbelo** [comment]
Are you releasing the console? The delphifmx is a dll, it will not raise the exception. You can use the console, instead.

**Comment by Ariel-MN** [comment]
I am using cmd with command >> python MainForm.py

**Comment by lmbelo** [comment]
Is there a FreeConsole() command before the Application main loop (Application.Run())?

e.g.:

``` 
MyForm.Show()
-->FreeConsole()<--
Application.Run()
```

**Comment by Ariel-MN** [comment]
I did it just like that, it seems errors due to non-existing components in the library are not caught.

**Comment by lmbelo** [comment]
@Ariel-MN I'm introducing a new error handling regarding Delphi run-time. I'm still running some tests, but I hope to get it working in our next release.

![image](https://user-images.githubusercontent.com/8376898/155432831-7308316d-dc66-4da5-8f4d-adbeeae740fe.png)

**Comment by lmbelo** [comment]
A new Delphi run-time exception was introduced to Python. The TNumberBox wrapper was introduced as well.
The following message represents a Delphi run-time exception, emitted by Delphi to Python.

![image](https://user-images.githubusercontent.com/8376898/155551431-e06e4467-695b-4dd0-a4c3-196879e2146b.png)

I'm holding for your confirmation before closing this issue.

**Comment by Ariel-MN** [comment]
I confirm, now the name of the unrecognized classes is displayed in a console error. And as a bonus the TNumberBox component was added to the library. Thank you very much for the effort!

**Comment by lmbelo** [comment]
Thank you for confirming that it works.
I'm closing this issue once it is resolved.
