### ISSUE TITLE
Win32 install broken

### ISSUE THREAD

**Issue by aerilox** [Embarcadero/DelphiVCL4Python#3]
On Python3.8 pip would not install Win32 lib folder. Manual download from github would result in a small file (only 3.3MB) and "NameError: name 'FileOpenDialog' is not defined" when running the sample.

**Comment by lmbelo** [comment]
Thank you for reporting.
Can you try again, please?

**Comment by lmbelo** [comment]
The #5 issue confirmed it is solved.
