### ISSUE TITLE
Issue with Delphi Rio 10.3.1 : install impossible

### ISSUE THREAD

**Issue by jassuli** [Embarcadero/DelphiVCL4Python#32]
Hi everyone, 

Seems that there is an install problem on Delphi Rio (10.3.1) as Vcl.DBGrids.TDBGrid do not own any ScaleValue method.

Any clue or Sydney+ is mandatory to use DelphiVCL4Python ?

Thanks a lot,
Jonas

**Comment by lmbelo** [comment]
@jassuli can you share all steps you've done to reproduce it?

**Comment by linces** [comment]
> Hi everyone,
> 
> Seems that there is an install problem on Delphi Rio (10.3.1) as Vcl.DBGrids.TDBGrid do not own any ScaleValue method.
> 
> Any clue or Sydney+ is mandatory to use DelphiVCL4Python ?
> 
> Thanks a lot, Jonas

Please, put some screenshot and the steps you follow.

**Comment by jassuli** [comment]
Sure, here you are !

1) Download Delphi4PythonExporter-main

2) Open the package Delphi10Rio

![01](https://user-images.githubusercontent.com/98476811/183858414-8ac1e9b0-a785-4c91-89ed-73d2bca10092.JPG)

3) Try to install, not working as  Vcl.DBGrids.TDBGrid is not found

![02](https://user-images.githubusercontent.com/98476811/183858698-128d2ab2-68f1-44f7-8731-0f677a2b55c3.JPG)

4) Verify if it's part of Rio : not part of Rio

![03](https://user-images.githubusercontent.com/98476811/183858823-d82c4570-44fa-47b3-9c1f-a6c19855ec60.JPG)

5) Verify it's part of Sydney : ok it's part of Sydney

![04](https://user-images.githubusercontent.com/98476811/183858962-b310694f-d7c5-4bc0-8fba-8d5470becd1c.JPG)

**Comment by lmbelo** [comment]
Oh, can you open a new issue in the [Delphi4PythonExporter](https://github.com/Embarcadero/Delphi4PythonExporter) repository, please?

**Comment by jassuli** [comment]
Oh snap ! Wrong depository. Will do.
Sorry and thanks !
