### ISSUE TITLE
command line

### ISSUE THREAD

**Issue by limelect** [Embarcadero/DelphiVCL4Python#38]
I run setup.py with guiPY 
I have this error for instalation

C:\Python\Python36-32\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'license_files'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

could not find any info what to put in command line

ALSO TRIED python setup.py install

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\LimElect>cd G:\python\DelphiVCL4Python-main

C:\Users\LimElect>g:

G:\python\DelphiVCL4Python-main>python setup.py install
  File "setup.py", line 23
    retvalue = exec(opffilecontents, gbals, lcals)
                  ^
SyntaxError: invalid syntax

G:\python\DelphiVCL4Python-main>

**Comment by limelect** [comment]
Tried your suggestion
pip install delphivcl


G:\python\DelphiVCL4Python-main>pip install delphivcl
Collecting delphivcl
  Downloading https://files.pythonhosted.org/packages/02/df/a84891eb0c278e315bdd
eedc7d0ea83574fb55dea7437e686a4883893f55/delphivcl-0.1.19.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\limelect\appdata\local\temp\pip-build-zew_nt\delphivcl\setu
p.py", line 32
        return f"DelphiVCL_{platmacshort}{os.sep}{sfilename}"
                                                            ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\limelect
\appdata\local\temp\pip-build-zew_nt\delphivcl\
You are using pip version 9.0.1, however version 22.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.

**Comment by Priyatham10** [comment]
Please try the same `pip install delphivcl` by getting out of that **DelphiVCL4Python-main** folder. It'll be installed successfully..

**Comment by limelect** [comment]
I do not understand in which folder am I supposed to put the source.?
G:/python is NOT the python.
my python is on C:\
So what you suggest is to put the source in c:\python?

**Comment by limelect** [comment]
tried
above C:\Python\Python36-32


Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\LimElect>cd C:\Python

C:\Python>pip install delphivcl
Collecting delphivcl
  Using cached https://files.pythonhosted.org/packages/02/df/a84891eb0c278e315bd
deedc7d0ea83574fb55dea7437e686a4883893f55/delphivcl-0.1.19.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\limelect\appdata\local\temp\pip-build-cm92fq\delphivcl\setu
p.py", line 32
        return f"DelphiVCL_{platmacshort}{os.sep}{sfilename}"
                                                            ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\limelect
\appdata\local\temp\pip-build-cm92fq\delphivcl\
You are using pip version 9.0.1, however version 22.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.

C:\Python>

**Comment by limelect** [comment]
What a directory has to do with install?

**Comment by Priyatham10** [comment]
When you install it in the repository directory, it installs from the repository's setup file instead of the remote pip wheel file. Please create a new conda environment and try to install directly using `pip install delphivcl` without downloading the reporistory zip file..

**Comment by limelect** [comment]
Sorry I am a Delphi developer and I am not aware of "conda environment "
If it will not be strait forward I will give up.
P.S I have installed already some other packages with guiPY  with no problems
thanks

**Comment by Priyatham10** [comment]
Installing conda is very straight-forward. Go to this link: https://docs.conda.io/en/latest/miniconda.html#latest-miniconda-installer-links to download the installer. Go to https://conda.io/projects/conda/en/stable/user-guide/install/index.html#regular-installation for Installation instructions for OS platform of your choice.

Finally checkout their cheatsheet to create new "conda environments" at: https://conda.io/projects/conda/en/stable/user-guide/cheatsheet.html

**Comment by limelect** [comment]
Thanks

**Comment by limelect** [comment]
well i decieded to wait for a fix

**Comment by lmbelo** [comment]
Please, share which Python version and O.S. you are using.

**Comment by lmbelo** [comment]
Working fine here:

![image](https://user-images.githubusercontent.com/8376898/202192765-d7d44e61-861e-4802-9f27-2dcfdb49a708.png)

**Comment by limelect** [comment]
Python 3.6.3 i can't update since i use window 7 and not going to change

**Comment by lmbelo** [comment]
You can try it on Python 3.7 onward.

**Comment by limelect** [comment]
I already checked on this page all need above window 7
https://www.python.org/downloads/windows/
And Python 3.7 do not have an installation
If you know of one that I can download with installation

**Comment by lmbelo** [comment]
Sorry, I just reviewed your post and I see that you're using a cached version (old version) of Delphi VCL. Try to reinstall it to the latest version.

**Comment by limelect** [comment]
Old version is D10.2.3 OLD?

**Comment by limelect** [comment]
!9.07.2022 the time i down loaded

**Comment by limelect** [comment]
It was my Python version. Now I have ver 3.8 for window 7

**Comment by limelect** [comment]
Fixed
