### ISSUE TITLE
stringgrid who atributes into python?

### ISSUE THREAD

**Issue by 3cubos** [Embarcadero/DelphiVCL4Python#40]
in delphi:

  with DrawGrid1 do
  begin
    Cells[0,0] := 'ID';
    Cells[1,0] := 'Name';
    Cells[0,1] := '5';
    Cells[1,1] := 'Marxcelo';
  end;

**Comment by 3cubos** [comment]
> in delphi:
> 
> with DrawGrid1 do begin Cells[0,0] := 'ID'; Cells[1,0] := 'Name'; Cells[0,1] := '5'; Cells[1,1] := 'Marxcelo'; end;

thank you, i solved it
thank you, i solved it

**Comment by Priyatham10** [comment]
Hi @3cubos .
Great, you figured out the solution. If your issue is resolved, please close it.
