### ISSUE TITLE
32 bit installation problem with solution

### ISSUE THREAD

**Issue by maxkleiner** [Embarcadero/DelphiVCL4Python#5]
after install with pip in 32 environment we get :
Exception: <class 'ValueError'>: DelphiVCL module not found. Try to reinstall the delphivcl package

Solution:
copy the delphivcl.pyd (3.75 MB) and create a win32 dir in python37-32\\lib\site-packages\delphivcl\win32\delphivcl.pyd

checked: eg.execStr('loader= importlib.machinery.ExtensionFileLoader("DelphiVCL",'+VCLHOME+')') :+1:

**Comment by lmbelo** [comment]
Hi, @maxkleiner.
Thanks for your report and contribution.
I'm working in a fix.

**Comment by lmbelo** [comment]
@maxkleiner,

can you try again, please?

**Comment by maxkleiner** [comment]
Hi Lucas, Yeah, tested with -0.1.31 and it works too on 32 bit! :+1: 
Thanks, Max

**Comment by lmbelo** [comment]
@maxkleiner, hank you for the confirmation.
