### ISSUE TITLE
Error when changing VCL styles. DelphiVCL 1.0.3

### ISSUE THREAD

**Issue by IanC216** [Embarcadero/DelphiVCL4Python#57]
This issue has already been raised (issue #50, on March 18th by @fansxs). I started a discussion on the same topic, and @lmbelo asked me to raise it as an issue again.

The ActivityIndicator.py demo crashes when I try to change style. The "**__on_load_style_click**" function crashes at line: 
"**valid_style, style_info = self.__sm.IsValidStyle(style_file_path)**". 
Python (v3.10) returns the error message "TypeError: cannot unpack non-iterable bool object". 

Removing the "**style_info**" variable allows the line to run, but then a different error is raised at the line "**self.__sm.LoadFromFile(style_file_path)**" :

  TypeError: Call "LoadFromFile" returned a value that could not be converted to Python 
  Error: Unsupported conversion from TValue to Python value

Here is my version of the code: 
![image](https://github.com/Embarcadero/DelphiVCL4Python/assets/108543693/ba7109b9-07df-465a-8177-8f4bdb4fc6c6)

**Comment by IanC216** [comment]
@lmbelo Some more information that might be useful to you.  When I run activityindicator.py from the console rather than in PyCharm, I get a different error. This appears immediately after choosing a valid folder from the 'Select the VCL Styles directory' dialog.
![image](https://github.com/Embarcadero/DelphiVCL4Python/assets/108543693/b21495cc-33bb-4d15-842c-809d4f861afc)

**Comment by MGBergweiler** [comment]
Using a freshly compile pyd from the current version found in Github gives no error any more. And browsing the history of WrapVclThemes.pas gives no clue why it does not work in delphivcl.pyd 1.03.

**Comment by MGBergweiler** [comment]
I must rectify my comment from 06 AUG 2023: a fresh compile of version 1.03 does not work, and also not for the new release version 1.04 (and also not directly from PIP install delphivcl)!

The source code for D4P is found in P4D, and we must note that there are three "official" repositories of P4D:
   - GetIt repository: old version 1.0, VCL styles works fine.
   - PyScripter GitHub repository: also works (last commit 02 AUG 2023)
   - Embarcaderor GitHub repository: fails (last commit 03 SEP 2023)

The source code for WrapVclThemes.pas is the same in PyScripter and Embarcadero, so I am not sure where problem is.

**Comment by lmbelo** [comment]
@MGBergweiler I'm able to reproduce the issue. I'm working on fixing it.

**Comment by MGBergweiler** [comment]
@lmbelo I just found out that by disabling $DEFINE EXPOSE_MEMBERS, the method IsValidStyle_Wrapper now does get called, and the problem is gone.

**Comment by lmbelo** [comment]
Right! The statically wrapped method is being overridden by the dynamically exposed method.
I got this fixed. It will be available in next release.

**Comment by IanC216** [comment]
Thanks for taking the time to address this issue. Any idea when the next
release will be available?

**Comment by lmbelo** [comment]
@IanC216 we are planning an emergency release for the current week.

**Comment by lmbelo** [comment]
@MGBergweiler and @IanC216, there's a new version available on pypi. Can you confirm it works on this latest version, please?

**Comment by MGBergweiler** [comment]
Thanks, is working fine here!
