### ISSUE TITLE
VSCode intellisense not friendly

### ISSUE THREAD

**Issue by iperov** [Embarcadero/DelphiVCL4Python#65]
there are no symbols in delphivcl package
so developing in delphivcl will be very uncomfortable.

![Code_2023-08-22_21-27-31](https://github.com/Embarcadero/DelphiVCL4Python/assets/8076202/1a4c1706-53ec-4a8e-8525-4e13647a0c81)

and pyqt for comparison:

![Code_2023-08-22_21-29-08](https://github.com/Embarcadero/DelphiVCL4Python/assets/8076202/c97d6247-7329-4b26-a7b0-ccf586d671bc)

so currently delphivcl is not a game changer for python

**Comment by lmbelo** [comment]
@iperov we have added type hints to the priority list. I will get you updated.

**Comment by iperov** [comment]
thx cool

**Comment by lmbelo** [comment]
@iperov this task is complete and will be available in next release.

**Comment by lmbelo** [comment]
@iperov by the way, it would be superb to see VCL and/or FMX in your projects. Let me know if there is something that I can do.

**Comment by iperov** [comment]
@lmbelo 

I've already tried vcl/fmx. 
https://github.com/Embarcadero/DelphiVCL4Python/issues/66
Compared to qt, it lacks various layout and size limiters that allow elements to look decent when the window is resized or when new dynamic elements appear.
The person suggests to write such layouts and limiters manually.
It feels like the original design of the vcl/fmx architecture is designed for fixed element sizes. 
Don't you think this approach is outdated for 2k23 ?

**Comment by FMXExpress** [comment]
I don't agree with your assertions. I've built hundreds (maybe thousands) of layouts in FMX. It is fully responsive using the Align property.

**Comment by iperov** [comment]
> I've built hundreds (maybe thousands) of layouts in FMX

said the developer of this framework.
Now show the fmx-python user who created thousands of apps. :D

> Use the form designer

i have no forms to design. My views are dynamic and depends on data, thus they are built in mind. Is fmx suitable for such task?

**Comment by lmbelo** [comment]
@iperov we also have plans to take VCL and FMX for back-end GUI option. Once we get it done, you will be able to use VCL and FMX to display data with easy.

**Comment by iperov** [comment]
@FMXExpress yes, there is not enough documentation on how to create and manipulate dynamic gui from code.

Maybe I'm too hardcore if I'm creating a GUI from code? Is this not mainstream?

by the way for my last project (DeepXTools) I built my own GUI system(wrapper) on top of Qt framework to create dynamic declarable tree-like GUI from code while maintaining maximum flexibility.

example:

https://github.com/Embarcadero/DelphiVCL4Python/assets/8076202/fdaea878-f5f4-411b-8329-81bcd709fafa

**Comment by lmbelo** [comment]
@iperov the stub file is now available as part of the VCL for Python package. Can you test it, please?

**Comment by iperov** [comment]
@lmbelo now works

**Comment by lmbelo** [comment]
> @lmbelo now works 

Cool xP
