### ISSUE TITLE
Error when running "SampleFormDesignExport"

### ISSUE THREAD

**Issue by drdanley** [Embarcadero/DelphiVCL4Python#9]
I have been trying to run the SampleFormDesignExport demonstration. I am using Delphi 11 and Python 3.9 (64 bit). I am a fairly experience (but not expert) Delphi programmer but a newbie to Python.
The program is loaded fairly deep on my G drive.
Everything works up through the export. I open MainForm.py in PyScripter and add the code to execute, but I get an error when I try to run:
"Remote Server is not connected. Please reinitialize or disconnect the remote server."

The error occurs somewhere in the line that starts: "self.LoadProps"
I ran using External Run and it gave me an error code "0EEDFADE."
I have tried using both Win32 and Win64 options on Delphi, and I have tried the same thing with Delphi 10.4.
I re-watched the webinar section and am doing everything the same, so maybe it is a Python configuration error.
Any assistance would be appreciated.

**Comment by hsauro** [comment]
I've seen that error in pyscripter. Does the popup window have an abort button? If so I just click that then try to run it again. That works for me.

**Comment by lmbelo** [comment]
@drdanley as @hsauro said, the "Remote Server is not connected. Please reinitialize or disconnect the remote server." comes up from PyScripter IDE. It may happen due to an error while your script is running.
I will try it again, but it was working without further issues.
Stay in touch :D

**Comment by drdanley** [comment]
Thanks for the help but no joy yet. If I click abort and run again, same thing happens. I tried running from command line and it it just goes back to a command line (no errors). I tried the same thing with ToggleSwitch demo and same errors, so I am thinking it is some sort of python configuration error. Is there anything that a newbie might have forgotten when installing python 3.9 or pyscripter?

**Comment by lmbelo** [comment]
hmm... that's odd. Are you running the latest version from PYPI?

**Comment by lmbelo** [comment]
I have just reinstalled delphivcl using the latest version at PYPI and it works fairly well. 
See the image bellow:

![Screen Shot 2022-01-20 at 20 21 26](https://user-images.githubusercontent.com/8376898/150437738-0b7ed651-06f3-4d0a-8ccd-6de2cbc9b36f.png)

**Comment by drdanley** [comment]
Okay. It might be time to uninstall everything except Delphi and do a clean install.  Thanks for your help.

**Comment by drdanley** [comment]
I uninstalled Python 3.9, delphivcl, python4delphi and pyscripter.
Reinstalled everything (except with Python 10.2) and...
It works!.
Thanks for the support.  I have an immediate project that this can be used in.
- Doug
